-- Número entero legible para cada ticket (#1, #2, ...). El uuid sigue siendo
-- la clave primaria: lo referencian ticket_status_history, ticket_asignados,
-- ticket_email_notifications, puedo_ver_ticket() y el realtime, así que cambiar su
-- tipo sería mucho más riesgoso que agregar esta columna aparte.
alter table tickets add column numero bigint;

-- Los tickets existentes se numeran en orden de creación.
update tickets t
set numero = n.numero
from (select id, row_number() over (order by created_at, id) as numero from tickets) n
where t.id = n.id;

alter table tickets alter column numero set not null;
alter table tickets alter column numero add generated by default as identity;
alter table tickets add constraint tickets_numero_key unique (numero);

-- La secuencia arranca después del último número asignado arriba.
select setval(
  pg_get_serial_sequence('tickets', 'numero'),
  coalesce((select max(numero) from tickets), 0) + 1,
  false
);
