-- Número entero legible para cada ticket (#1, #2, ...). El uuid sigue siendo
-- la clave primaria: lo referencian ticket_status_history, ticket_asignados,
-- ticket_email_notifications, puedo_ver_ticket() y el realtime, así que cambiar su
-- tipo sería mucho más riesgoso que agregar esta columna aparte.
--
-- Es idempotente porque la columna se llegó a crear a mano en producción antes
-- de pasar por db push: completa solo lo que falte y respeta los números que
-- ya existan.
alter table tickets add column if not exists numero bigint;

-- Los tickets sin número se numeran en orden de creación, después del mayor
-- número ya asignado (si no había ninguno, empiezan en 1).
update tickets t
set numero = n.numero
from (
  select id,
         (select coalesce(max(numero), 0) from tickets) + row_number() over (order by created_at, id) as numero
  from tickets
  where numero is null
) n
where t.id = n.id;

alter table tickets alter column numero set not null;

do $$
begin
  -- pg_get_serial_sequence es no nulo si la columna ya es identity o serial.
  if pg_get_serial_sequence('public.tickets', 'numero') is null then
    alter table public.tickets alter column numero add generated by default as identity;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.tickets'::regclass and contype = 'u'
      and conkey = array[(select attnum from pg_attribute where attrelid = 'public.tickets'::regclass and attname = 'numero')]
  ) then
    alter table public.tickets add constraint tickets_numero_key unique (numero);
  end if;
end $$;

-- La secuencia sigue después del último número asignado.
select setval(
  pg_get_serial_sequence('public.tickets', 'numero'),
  coalesce((select max(numero) from tickets), 0) + 1,
  false
);
